-- begin TESTPROJECT_ORDER
alter table TESTPROJECT_ORDER add constraint FK_TESTPROJECT_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references TESTPROJECT_CUSTOMER(ID)^
create index IDX_TESTPROJECT_ORDER_CUSTOMER on TESTPROJECT_ORDER (CUSTOMER_ID)^

alter table TESTPROJECT_ORDER add constraint FK_TESTPROJECT_ORDER_NOMENCLATURE foreign key (NOMENCLATURE_ID) references TESTPROJECT_NOMENCLATURE(ID)^
create index IDX_TESTPROJECT_ORDER_NOMENCLATURE on TESTPROJECT_ORDER (NOMENCLATURE_ID)^
-- end TESTPROJECT_ORDER